version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: hiagocarlos/quote-api:1.0
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: hiagocarlos/quote-ui:1.0
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - api